# Generated by Django 5.0.2 on 2024-02-15 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts', to='blog.post', verbose_name='пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'прочитанные посты',
                'verbose_name_plural': 'прочитанные посты',
            },
        ),
        migrations.AddConstraint(
            model_name='postuser',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='Unique user and post'),
        ),
    ]
